[keybinds]
# Applications and session
"Mod+Return" = { action = "spawn:systemd-run --user emacsclient -ca \"\"", repeat = false }
"Mod+E" = { action = "spawn:systemd-run --user pcmanfm" }
"Mod+T" = { action = "spawn:xdg-terminal-exec" }
"Mod+D" = "spawn:noctalia msg panel-toggle launcher"
"Mod+B" = { action = "spawn:wlr-which-key browsers" }
"Mod+Q" = { action = "window-close", repeat = false }
"Mod+Escape" = "session-quit"
"Mod+Shift+Escape" = { action = "shortcuts-inhibit-toggle", allow_when_inhibited = true, repeat = false }

# Focus and movement
"Mod+Left" = "window-focus-left"
"Mod+Down" = "window-focus-down"
"Mod+Up" = "window-focus-up"
"Mod+Right" = "window-focus-right"
"Mod+H" = "window-focus-left"
"Mod+J" = "window-focus-down"
"Mod+K" = "window-focus-up"
"Mod+L" = "window-focus-right"
"Mod+F1" = "window-focus-next"
"Mod+Shift+Left" = "column-move-left"
"Mod+Shift+Down" = "window-move-down"
"Mod+Shift+Up" = "window-move-up"
"Mod+Shift+Right" = "column-move-right"

# Window state and layout
"Mod+V" = { action = "window-toggle-floating", repeat = false }
"Mod+Shift+V" = { action = "window-focus-switch-floating", repeat = false }
"Mod+P" = { action = "window-toggle-pinned", repeat = false }
"Mod+M" = { action = "window-toggle-maximize", repeat = false }
"Mod+Shift+M" = { action = "window-toggle-maximize-to-edges", repeat = false }
"Mod+F" = { action = "window-toggle-fullscreen", repeat = false }
"Mod+Ctrl+F" = { action = "window-toggle-maximize", repeat = false }
"Mod+R" = "window-cycle-primary-extent"
"Mod+Shift+R" = "window-cycle-primary-extent-back"
"Mod+Comma" = "window-consume-left"
"Mod+Period" = "window-consume-right"
"Mod+WheelUp" = "window-focus-left"
"Mod+WheelDown" = "window-focus-right"
"Mod+O" = { action = "overview-toggle", repeat = false }

# Workspaces
"Mod+I" = "workspace-previous"
"Mod+U" = "workspace-next"
"Mod+Shift+I" = "window-move-to-workspace-previous"
"Mod+Shift+U" = "window-move-to-workspace-next"

"Mod+1" = "workspace-switch:1"
"Mod+2" = "workspace-switch:2"
"Mod+3" = "workspace-switch:3"
"Mod+4" = "workspace-switch:4"
"Mod+5" = "workspace-switch:5"
"Mod+6" = "workspace-switch:6"
"Mod+7" = "workspace-switch:7"
"Mod+8" = "workspace-switch:8"
"Mod+9" = "workspace-switch:9"
"Mod+Shift+1" = "window-move-to-workspace:1"
"Mod+Shift+2" = "window-move-to-workspace:2"
"Mod+Shift+3" = "window-move-to-workspace:3"
"Mod+Shift+4" = "window-move-to-workspace:4"
"Mod+Shift+5" = "window-move-to-workspace:5"
"Mod+Shift+6" = "window-move-to-workspace:6"
"Mod+Shift+7" = "window-move-to-workspace:7"
"Mod+Shift+8" = "window-move-to-workspace:8"
"Mod+Shift+9" = "window-move-to-workspace:9"

# Scratchpad
"Mod+Shift+Space" = { action = "window-move-to-scratchpad", repeat = false }
"Mod+Space" = "scratchpad-toggle"
"Mod+Ctrl+Space" = { action = "window-restore-from-scratchpad", repeat = false }
"Mod+Tab" = "scratchpad-focus-next"

# Brightness keys
"XF86MonBrightnessDown" = { action = "spawn:noctalia msg brightness-down 10", allow_when_locked = true }
"XF86MonBrightnessUp" = { action = "spawn:noctalia msg brightness-up 10", allow_when_locked = true }
# Volume Keys
"XF86AudioRaiseVolume" = "spawn:noctalia msg volume-up"
"XF86AudioLowerVolume" = "spawn:noctalia msg volume-down"
"XF86AudioMute" = "spawn:noctalia msg volume-mute"
# Player keys
"XF86AudioPlay" = "spawn:noctalia msg media toggle"
"XF86AudioNext" = "spawn:noctalia msg media next"
"XF86AudioPrev" = "spawn:noctalia msg media previous"

# Toggle cheatsheet
"Mod+Slash" = "cheatsheet-toggle"
