#!/usr/bin/env bash
set -euo pipefail

conf_dir="${XDG_CONFIG_HOME:-$HOME/.config}/nix"

# Unmatched globs expand to nothing instead of the literal pattern
shopt -s nullglob

declare -A existing
for f in "$conf_dir"/nix.conf.backup*; do
    existing[$f]=1
done

nix run github:numtide/nix-auth -- login

new_backups=()
for f in "$conf_dir"/nix.conf.backup*; do
    if [[ -z ${existing[$f]:-} ]]; then
        new_backups+=("$f")
    fi
done

if (( ${#new_backups[@]} == 0 )); then
    echo "No new backup files found, nothing to remove."
    exit 0
fi

echo "Backup files generated by nix-auth:"
printf '  %s\n' "${new_backups[@]}"

read -r -p "Remove them? [Y/n] " answer
case "${answer,,}" in
    ""|y|yes) rm -f -- "${new_backups[@]}" && echo "Removed." ;;
    *)        echo "Left in place." ;;
esac
